const BLOG_CaTEGORIES = [
  "Technology",
  "Health",
    "Travel",
    "Food",
    "Lifestyle",
    "Education",
    "Finance",
    "Entertainment",
    "Sports",
    "Fashion",
    "Science",
    "Politics",
    "Art",
    "History",
    "Business",
    "Environment",
    "Culture",
    "Music",
    "Photography",
    "Gaming",
    "Other",
];
export { BLOG_CaTEGORIES };